### ISSUE TITLE
Working with Browser mod's fire-dom-event

### ISSUE THREAD

**Issue by netsoft-ruidias** [bhuebschen/fab-card#2]
This doesn't seem to be working:

```yaml
type: custom:fab-card
button_color: '#FF5722'
icon_color: '#FFFFFF'
active_color: '#2257FF'
icon: mdi:plus
action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: TESTE
      dismissable: true
      style: |
        --popup-border-radius: 10px;
        --popup-border-width: 0px;
        --popup-background-color: transparent;
        --popup-padding-x: 10px;
        --ha-card-background: rgba(var(--color-theme),0.9);
      card_mod:
        style:
          ha-dialog$: |
            div.mdc-dialog__scrim {
              backdrop-filter: blur(15px) !important;
              -webkit-backdrop-filter: blur(15px) !important;
            }
      content:
        type: custom:mushroom-template-card
        primary: Hello, {{user}}
        secondary: How are you?
        icon: mdi:home
```

Can you add the possibility to work with `fire-dom-event` events?

More info: https://github.com/thomasloven/hass-browser_mod
