### ISSUE TITLE
Ability to Trigger Assist Pipeline

### ISSUE THREAD

**Issue by therealbiglou** [bhuebschen/fab-card#4]
Similar to being able to open Assist with voice listening from a standard HA button card, I'd love for the ability to have Assist be one of the actions FAB can trigger.

**Comment by bhuebschen** [comment]
I'm currently investigating how to realise this

**Comment by bhuebschen** [comment]
please try 1.0.4 and let me know if this works for you

**Comment by patienttruth** [comment]
Hello, I'm having trouble with this. Here's my config:

```
type: custom:fab-card
button_color: blue
icon_color: "#FFFFFF"
active_color: "#2257FF"
icon: mdi:assistant
action:
  action: assist
  start_listening: true
position: bottom-right
animation: bounce
```

nothing gets triggered though. Would you be willing to share a working config? Thanks!
